baseURL = "https://lkummer.github.io/Monochrome/"
title = "Monochrome"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "lander"
pygmentsUseClasses = true

[params]
  [params.footer]
    title = "About"
    text = """
    Monochrome Hugo Theme is a minimalistic Hugo theme for blogging.
    """
  [params.seo]
    category = "Hugo Theme"
    downloadURL = "#"
    versionEnv = "npm_package_version"
    operatingSystem = "Any"
    isFree = true
    license = "#"
    defaultAuthor = "Lior Kummer"
  [params.colors]
    primary-600 = "hsl(210, 45%, 40%)"
    primary-500 = "hsl(210, 45%, 43%)"
    primary-400 = "hsl(210, 40%, 48%)"
    accent-600 = "hsl(330, 60%, 43%)"
    accent-500 = "hsl(330, 60%, 46%)"
    accent-400 = "hsl(330, 60%, 50%)"
    accent-300 = "hsl(330, 35%, 80%)"
    accent-200 = "hsl(330, 33%, 82%)"
    accent-100 = "hsl(330, 30%, 85%)"
    background-900 = "hsl(30, 15%, 86%)"
    background-400 = "hsl(30, 18%, 88%)"
    background-300 = "hsl(30, 16%, 90%)"
    background-200 = "hsl(30, 14%, 92%)"
    background-100 = "hsl(30, 14%, 92%)"
    text-900 = "hsla(0, 0%, 0%, 0.75)"
    text-800 = "hsla(0, 0%, 0%, 0.7)"
    text-700 = "hsla(0, 0%, 0%, 0.65)"
    text-500 = "hsl(330, 60%, 43%)"
    text-400 = "hsl(330, 60%, 46%)"
    text-300 = "hsl(330, 60%, 50%)"
    text-200 = "hsla(0, 0%, 100%, 0.85)"
    text-100 = "hsla(0, 0%, 0%, 0.7)"
    highlight-text = "hsl(240, 35%, 99%)"
    highlight-background = "hsl(240, 13%, 14%)"
    highlight-comment = "hsl(250, 25%, 55%)"
    highlight-special = "hsl(180, 75%, 55%)"
    highlight-operator = "hsl(330, 95%, 75%)"
    highlight-literal = "hsl(250, 80%, 70%)"
  [params.graphics]
    favicon = "favicon.svg"
    logo = """
    <svg class="navbar-logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
      viewBox="5 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
    <style type="text/css">
      .st0{fill:#CCC9C6;}
      .st1{fill:#332518;}
    </style>
    <polygon class="st0" points="10.3,18 7,18 7,9.5"/>
    <polygon class="st1" points="13.7,18 13,19.8 13,20 11,20 11,19.8 7,9.5 7,20 5,20 5,4 7,4 12.4,18"/>
    <polygon class="st1" points="19,4 19,20 17,20 17,6 16.2,6 17,4"/>
    </svg>
    """

[menu]
  [[menu.main]]
    name = "Releases"
    url = "https://github.com/LKummer/Monochrome/releases"
  [[menu.footer]]
    name = "Releases"
    url = "https://github.com/LKummer/Monochrome/releases"

[taxonomies]
category = "categories"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
