baseURL = "https://gohugo.io"
title = "Hugo Themes"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "hugo-theme-boilerplate"
pygmentsUseClasses = true
sectionPagesMenu = "main"

[author]
  name = "Steve Francia"

[params]
  [params.site]
    indexSection = "article"
  [params.seo]
    description = "Monochrome theme demo website."
    logo = "logo.png"
    defaultImages = [
      "image-1x1.png",
      "image-4x3.png",
      "image-16x9.png"
    ]

[taxonomies]
tag = "tags"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
